# Tensor Operation in PyTorch

In [5]:
import torch

# Create a tensor
x = torch.tensor([[1, 2], [3, 4]])
print("x=", x)

# Tensor addition
y = torch.tensor([[5, 6], [7, 8]])
print("y=", y)
print("x+y=", x + y)

# Matrix multiplication
z = torch.matmul(x, y.T)
print("x*y=", z)

# GPU operations
if torch.cuda.is_available():
    x = x.to("cuda")  # Move tensor to GPU


x= tensor([[1, 2],
        [3, 4]])
y= tensor([[5, 6],
        [7, 8]])
x+y= tensor([[ 6,  8],
        [10, 12]])
x*y= tensor([[17, 23],
        [39, 53]])


# Tensor Operation in TensorFlow

In [7]:
import tensorflow as tf

# Create a tensor
x = tf.constant([[1, 2], [3, 4]])
print(x)

# Tensor addition
y = tf.constant([[5, 6], [7, 8]])
print(y)
print(tf.add(x, y))

# Matrix multiplication
z = tf.matmul(x, tf.transpose(y))
print(z)


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[17 23]
 [39 53]], shape=(2, 2), dtype=int32)
