In [1]:
# !pip install numpy

In [2]:
import numpy as np

# 1. ReLU - Rectified Linear Unit (Hidden Layer)

In [3]:
def relu(x):
    return np.maximum(0, x)


In [4]:
relu(10)

10

In [5]:
relu(-10)

0

In [6]:
relu(np.array([-1, 0, 1, 2]))

array([0, 0, 1, 2])

# 2. Leaky ReLU (Hidden Layer)

Leaky ReLU allows a small, positive gradient when the unit is not active.

In [7]:
def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, x * alpha)


In [8]:
leaky_relu(-1)

array(-0.01)

In [9]:
leaky_relu(np.array([-1, 0, 1, 2]))

array([-0.01,  0.  ,  1.  ,  2.  ])

# 3. ELU - Exponential Linear Unit (Hidden Layer)

ELU has a small slope for negative values, unlike ReLU, to avoid the dying ReLU problem.

In [10]:
def elu(x, alpha=1.0):
    return np.where(x > 0, x, alpha * (np.exp(x) - 1))

In [11]:
elu(5)

array(5.)

In [12]:
elu(np.array([-1, 0, 1, 2]))

array([-0.63212056,  0.        ,  1.        ,  2.        ])

# 4. Sigmoid (Output Layer & Binaryclass Problem)

In [13]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


In [14]:
sigmoid(np.array([-1, 0, 1, 2]))

array([0.26894142, 0.5       , 0.73105858, 0.88079708])

# 5. Softmax (Output Layer & Multiclass Problem)

Softmax converts a real vector to a vector of categorical probabilities.

In [15]:
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)


In [16]:
proba = softmax(np.array([-1, 0, 1, 2]))
proba

array([0.0320586 , 0.08714432, 0.23688282, 0.64391426])

In [17]:
sum(proba)

1.0

# 6. Swish (Hidden Layer)

Swish is a self-gated activation function.

In [18]:
def swish(x, beta=1.0):
    return x * sigmoid(beta * x)


In [19]:
swish(5)

4.966535745378576

In [20]:
swish(np.array([-1, 0, 1, 2]))

array([-0.26894142,  0.        ,  0.73105858,  1.76159416])

# 7. Linear (Output Layer)

Linear or identity activation function returns the input directly.

In [21]:
def linear(x):
    return x

In [22]:
linear(10)

10

# 8. Tanh (Hyperbolic Tangent)

In [23]:
def tanh(x):
    return np.tanh(x)

In [24]:
tanh(10)

0.9999999958776927

In [25]:
tanh([-1, 0, 1, 2])

array([-0.76159416,  0.        ,  0.76159416,  0.96402758])

In [26]:
import math

In [27]:
def tanh(x):
    result = (math.exp(x) - math.exp(-x)) / (math.exp(x) + math.exp(-x))
    return result

In [28]:
tanh(-1)

-0.7615941559557649